# when using the default proxy server port
local_backend: true

backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

publish_mode: editorial_workflow

# Local media storage (fallback)
media_folder: "src/assets/uploads"
public_folder: "src/assets/uploads"

# Cloudinary media library configuration
media_library:
  name: cloudinary
  config:
    cloud_name: ${CLOUDINARY_CLOUD_NAME}
    api_key: ${CLOUDINARY_API_KEY}
    multiple: false

collections:
  - name: "story_collection"
    label: "Collection"
    folder: "src/stories/collections"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Order"
        name: "order"
        widget: "number"
        required: true
      - label: "Visible"
        name: "isShow"
        widget: "boolean"
        required: true
      - label: "Stories"
        name: "stories"
        widget: "relation"
        required: true
        collection: "en_stories"
        search_fields: ["title"]
        value_field: "slug"
        display_fields: ["title"]
        multiple: true
        min: 1

  - name: "en_stories"
    label: "English Stories"
    folder: "src/stories/en"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true

      - label: "Category"
        name: "category"
        widget: "select"
        options:
          [
            "Puthi Literature",
            "Bengali Folktale",
            "Bengali Translation",
            "Indigenous Folktale",
            "Bengal Legend",
            "Hindu Mythology",
          ]
        required: true

      - label: "Language"
        name: "language"
        widget: "select"
        options: ["en", "bn"]
        required: true

      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true

  - name: "bn_stories"
    label: "Bengali Stories"
    folder: "src/stories/bn"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true

      - label: "Category"
        name: "category"
        widget: "select"
        options:
          [
            "Puthi Literature",
            "Bengali Folktale",
            "Bengali Translation",
            "Indigenous Folktale",
            "Bengal Legend",
            "Hindu Mythology",
          ]
        required: true

      - label: "Language"
        name: "language"
        widget: "select"
        options: ["en", "bn"]
        required: true

      - label: "Body"
        name: "body"
        widget: "markdown"
        required: true

  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true

      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        required: true

      - label: "Cover Image"
        name: "cover_image"
        widget: "object"
        required: false
        fields:
          - label: "Image"
            name: "src"
            widget: "image"
            required: false
            media_library:
              config:
                cloud_name: ${CLOUDINARY_CLOUD_NAME}
                api_key: ${CLOUDINARY_API_KEY}
                multiple: false
          - label: "Alt Text"
            name: "alt"
            widget: "string"
            required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
        media_library:
          config:
            cloud_name: ${CLOUDINARY_CLOUD_NAME}
            api_key: ${CLOUDINARY_API_KEY}
            multiple: false
        required: true
